server:
  port: 8085
  
app:
  attachments:
    base-dir: "C:/Users/dell/Desktop/Tickets-Microservices/attachment-service/src/main/resources/uplods"

spring:
  application:
    name: attachment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/attachment_db
    username: postgres
    password: kysz
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
